version: '3.7'

services:
  database:
    image: postgres
    container_name: database_ngcash
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ngcash
      - POSTGRES_DB=ngcash
    volumes:
      - pgdata:/data/postgres
  server:
    build:
      context: ./server
    ports:
      - 3333:3333
    container_name: server
    volumes:
      - .:/usr/server
    links:
      - database
    depends_on:
      - database
  web:
    build:
      context: ./web
    ports:
      - '3000:3000'
    container_name: web
    stdin_open: true
    volumes:
      - .:/usr/web

volumes:
  pgdata:
    driver: local
